service: asx-db-sl

frameworkVersion: '3'

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-dynamodb-local
  - serverless-dynamodb-autoscaling
custom:
  tableName: 'tickers-table-${self:provider.stage}'
  wsgi:
    app: flask/app.app
  dynamodb:
    start:
      migrate: true
    stages:
      - dev
  pythonRequirements:
    dockerizePip: non-linux
    layer: true
  capacities:
    - table: TickersTable # Dynamodb Resource
      read:
        minimum: 10    # Minimum read capacity
        maximum: 20  # Maximum read capacity
        usage: 0.75   # Target usage percentage
      write:
        minimum: 10    # Minimum write capacity
        maximum: 20  # Maximum write capacity
        usage: 0.75   # Target usage percentage
provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-southeast-2
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [TickersTable, Arn]
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
          Resource:
            - !Sub "${TickersTable.Arn}/index/*"
  environment:
    TICKERS_TABLE: ${self:custom.tableName}
package:
  patterns:
    - '!.dynamodb/**'
functions:
  api:
    handler: wsgi_handler.handler
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
  auto_update:
    handler: dev/dev.autoUpdate
    layers:
    - {Ref: PythonRequirementsLambdaLayer}
    events:
      - schedule: cron(0/2 * ? * * *)
  init:
    handler: dev/dev.init
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
    events:
      - http:
          path: api/init/
          method: POST
          async: true
    timeout: 600


resources:
  Resources:
    TickersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: LastUpdated
            AttributeType: S
          - AttributeName: ASX code
            AttributeType: S
          - AttributeName: GSI1PK
            AttributeType: S
        KeySchema:
          - AttributeName: ASX code
            KeyType: HASH
        GlobalSecondaryIndexes:
            - IndexName: LastUpdatedIndex
              KeySchema:
                - AttributeName: GSI1PK
                  KeyType: HASH
                - AttributeName: LastUpdated
                  KeyType: RANGE
              Projection:
                ProjectionType: KEYS_ONLY
              ProvisionedThroughput:
                ReadCapacityUnits: 10
                WriteCapacityUnits: 10
        ProvisionedThroughput:
          ReadCapacityUnits: 15
          WriteCapacityUnits: 15
        TableName: ${self:custom.tableName}

