service: asx-db-sl

frameworkVersion: '3'


plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-dynamodb-local
custom:
  tableName: 'tickers-table-${self:provider.stage}'
  wsgi:
    app: app.app
  pythonRequirements:
    dockerizePip: non-linux
  dynamodb:
    start:
      migrate: true
    stages:
      - dev

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: ap-southeast-2
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ TickersTable, Arn ]
  environment:
    TICKERS_TABLE: ${self:custom.tableName}

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
  init:
    handler: handler.init 
    events:
      - http: 
          path: /db/init
          method: ANY
          async: true
    timeout: 600
    

          
  
resources:
  Resources:
    TickersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: "ASX code"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "ASX code"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}
