service: asx-db-sl

frameworkVersion: '3'

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-dynamodb-local
  - serverless-dynamodb-autoscaling
custom:
  tableName: 'tickers-table-${self:provider.stage}'
  wsgi:
    app: flask/app.app
  dynamodb:
    start:
      migrate: true
    stages:
      - dev
  pythonRequirements:
    dockerizePip: non-linux
    layer: true
  capacities:
    - table: TickersTable # Dynamodb Resource
      index: ['LastUpdatedIndex', 'MarketCapIndex', 'ListingDateIndex', 'GroupIndex', 'NameIndex', TickerIndex]
      read:
        minimum: 1    # Minimum read capacity
        maximum: 20  # Maximum read capacity
        usage: 0.75   # Target usage percentage
      write:
        minimum: 1    # Minimum write capacity
        maximum: 20  # Maximum write capacity
        usage: 0.75   # Target usage percentage
provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-southeast-2
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [TickersTable, Arn]
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
          Resource:
            - !Sub "${TickersTable.Arn}/index/*"
  environment:
    TICKERS_TABLE: ${self:custom.tableName}
    API_GATEWAY_BASE_PATH: dev/
package:
  patterns:
    - '!.dynamodb/**'
functions:
  api:
    handler: wsgi_handler.handler
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
  autoUpdate:
    handler: dev/dev.autoUpdate
    layers:
    - {Ref: PythonRequirementsLambdaLayer}
    events:
      - schedule: cron(0/2 * ? * * *)
    memorySize: 512
  init:
    handler: dev/dev.init
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
    events:
      - http:
          path: api/init/
          method: POST
          async: true
    timeout: 600


resources:
  Resources:

    TickersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: LastUpdated
            AttributeType: S
          - AttributeName: ASX code
            AttributeType: S
          - AttributeName: GSI1PK
            AttributeType: S
          - AttributeName: Market Cap
            AttributeType: N
          - AttributeName: GICs industry group
            AttributeType: S
          - AttributeName: Listing date
            AttributeType: S
          - AttributeName: Company name
            AttributeType: S
        KeySchema:
          - AttributeName: ASX code
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

        GlobalSecondaryIndexes:
            - IndexName: LastUpdatedIndex
              KeySchema:
                - AttributeName: GSI1PK
                  KeyType: HASH
                - AttributeName: LastUpdated
                  KeyType: RANGE
              Projection:
                ProjectionType: KEYS_ONLY
              ProvisionedThroughput:
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1

            - IndexName: MarketCapIndex
              KeySchema:
                - AttributeName: GSI1PK
                  KeyType: HASH
                - AttributeName: Market Cap
                  KeyType: RANGE
              Projection:
                ProjectionType: INCLUDE
                NonKeyAttributes:
                  - GICs industry group
                  - Listing date
                  - Company name
                  - Market Cap
              ProvisionedThroughput:
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1

            - IndexName: ListingDateIndex 
              KeySchema:
                - AttributeName: GSI1PK
                  KeyType: HASH
                - AttributeName: Listing date
                  KeyType: RANGE
              Projection:
                ProjectionType: INCLUDE
                NonKeyAttributes:
                  - GICs industry group
                  - Listing date
                  - Company name
                  - Market Cap
              ProvisionedThroughput:
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1

            - IndexName: GroupIndex
              KeySchema:
                - AttributeName: GSI1PK
                  KeyType: HASH
                - AttributeName: GICs industry group
                  KeyType: RANGE
              Projection:
                ProjectionType: INCLUDE
                NonKeyAttributes:
                  - GICs industry group
                  - Listing date
                  - Company name
                  - Market Cap
              ProvisionedThroughput:
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1

            - IndexName: NameIndex
              KeySchema:
                - AttributeName: GSI1PK
                  KeyType: HASH
                - AttributeName: Company name
                  KeyType: RANGE
              Projection:
                ProjectionType: INCLUDE
                NonKeyAttributes:
                  - GICs industry group
                  - Listing date
                  - Company name
                  - Market Cap
              ProvisionedThroughput:
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1

            - IndexName: TickerIndex
              KeySchema:
                - AttributeName: GSI1PK
                  KeyType: HASH
                - AttributeName: ASX code
                  KeyType: RANGE
              Projection:
                ProjectionType: INCLUDE
                NonKeyAttributes:
                  - GICs industry group
                  - Listing date
                  - Company name
                  - Market Cap
              ProvisionedThroughput:
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}

