service: asx-db-sl

frameworkVersion: '3'

custom:
  tableName: 'tickers-table-${self:provider.stage}'
  wsgi:
    app: flask/app.app
  dynamodb:
    start:
      migrate: true
    stages:
      - dev
  pythonRequirements:
    dockerizePip: non-linux
    layer: true

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-southeast-2
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ TickersTable, Arn ]
  environment:
    TICKERS_TABLE: ${self:custom.tableName}

package:
  individually: true
  exclude:
    - '**/*'
functions:
  api:
    handler: wsgi_handler.handler
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements

resources:
  Resources:
    TickersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: ASX code
            AttributeType: S
        KeySchema:
          - AttributeName: ASX code
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}
